package com.iandp.happy.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.iandp.happy.database.DBProductDao;
import com.iandp.happy.database.DBImageDao;
import com.iandp.happy.database.DBCategoryProductDao;
import com.iandp.happy.database.DBCostDao;
import com.iandp.happy.database.DBShopDao;
import com.iandp.happy.database.DBProductSimpleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        DBProductDao.createTable(db, ifNotExists);
        DBImageDao.createTable(db, ifNotExists);
        DBCategoryProductDao.createTable(db, ifNotExists);
        DBCostDao.createTable(db, ifNotExists);
        DBShopDao.createTable(db, ifNotExists);
        DBProductSimpleDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        DBProductDao.dropTable(db, ifExists);
        DBImageDao.dropTable(db, ifExists);
        DBCategoryProductDao.dropTable(db, ifExists);
        DBCostDao.dropTable(db, ifExists);
        DBShopDao.dropTable(db, ifExists);
        DBProductSimpleDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DBProductDao.class);
        registerDaoClass(DBImageDao.class);
        registerDaoClass(DBCategoryProductDao.class);
        registerDaoClass(DBCostDao.class);
        registerDaoClass(DBShopDao.class);
        registerDaoClass(DBProductSimpleDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
