package com.iandp.happy.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBIMAGE".
 */
public class DBImage {

    private Long id;
    private String path;
    private long productId;

    public DBImage() {
    }

    public DBImage(Long id) {
        this.id = id;
    }

    public DBImage(Long id, String path, long productId) {
        this.id = id;
        this.path = path;
        this.productId = productId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public long getProductId() {
        return productId;
    }

    public void setProductId(long productId) {
        this.productId = productId;
    }

}
