package com.iandp.happy.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBPRODUCT_SIMPLE".
 */
public class DBProductSimple {

    private Long id;
    private String name;
    private Double price;
    private Double amount;
    private Byte typeAmount;

    public DBProductSimple() {
    }

    public DBProductSimple(Long id) {
        this.id = id;
    }

    public DBProductSimple(Long id, String name, Double price, Double amount, Byte typeAmount) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.amount = amount;
        this.typeAmount = typeAmount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Byte getTypeAmount() {
        return typeAmount;
    }

    public void setTypeAmount(Byte typeAmount) {
        this.typeAmount = typeAmount;
    }

}
